### PR TITLE
fix(screentracker): make writeStabilize Phase 1 non-fatal when agents don't echo input

### LINKED ISSUE #123: failed to send message: failed to send message: failed to wait for screen to stabilize: timeout waiting for condition
when i send localhost:3284/message with body: 
{
    "content": "Hello, agent!",
    "type": "user"
}, 
then output
{
	"$schema": "http://localhost:3284/schemas/ErrorModel.json",
	"title": "Internal Server Error",
	"status": 500,
	"detail": "unexpected error occurred",
	"errors": [
		{
			"message": "failed to send message: failed to send message: failed to wait for screen to stabilize: timeout waiting for condition"
		}
	]
},it looks like something wrong with server, please help me

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes #123.

## Changes

- Make Phase 1 (echo detection) of `writeStabilize` non-fatal on timeout -- proceed to Phase 2 instead of returning HTTP 500
- Guard non-fatal path with `errors.Is(err, util.WaitTimedOut)` so context cancellation still propagates
- Reduce Phase 1 timeout from 15s to 2s (terminal echo is near-instant)
- Extract `writeStabilizeEchoTimeout` and `writeStabilizeProcessTimeout` constants
- Log at Info level (not Warn) since non-echoing agents hit this on every message
- Add doc comment on `formatPaste` in `claude.go` documenting the ESC limitation with TUI selection prompts
- Add tests for non-echoing agents (reacts, unresponsive, context-cancelled)

## Known limitation

For TUI selection prompts (numbered/arrow-key lists), this fix eliminates the 500 but does **not** deliver the correct selection -- the `\x1b` (ESC) in bracketed paste cancels the selection widget. The correct approach is `MessageTypeRaw`. Documented via a comment on `formatPaste` in `lib/httpapi/claude.go`.

Also discovered a separate issue during smoke-testing: #209 (fixed in #215, included in this branch).

> 🤖 Written by a Coder Agent. Reviewed by a human and a veritable army of robots.

### CODE REVIEW

File: lib/screentracker/pty_conversation.go [hunk 1]
```diff
@@ -438,14 +469,25 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
 		}
 		return false, nil
 	}); err != nil {
-		return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
+		if !errors.Is(err, util.WaitTimedOut) {
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go:478]: **P2** The `errors.Is(err, util.WaitTimedOut)` guard is the critical correctness invariant of this PR, and it has no test. If someone simplifies this to `if err != nil { /* log and continue */ }`, context cancellation during Phase 1 would be silently swallowed: the warning log fires, a spurious `\r` is written, and Phase 2 runs against a cancelled context. No existing test would catch it.

Missing test: cancel the context during Phase 1 (agent never echoes), assert `Send` returns an error wrapping `context.Canceled` (not a Phase 2 error). *(Bisky P2)*

> 🤖

File: lib/screentracker/pty_conversation_test.go [hunk 2]
```diff
@@ -447,7 +449,140 @@ func TestMessages(t *testing.T) {
...
+				st.MessagePartText{Content: "\x1b[201~", Hidden: true},
+			)
+
+			// Then: Send succeeds, but the selection was cancelled
+			// by ESC — option "2" was never delivered to the
+			// selection handler.
+			assert.True(t, selectionCancelled,
+				"ESC in bracketed paste cancels TUI selection prompts; "+
+					"use MessageTypeRaw for selection prompts instead")
+		})}
```
Comment (mafredri) [inline lib/screentracker/pty_conversation_test.go]: **P2** All three new subtests are indented one extra tab level versus siblings in `TestMessages`. Line 585 jams closing braces into `})}` instead of separate lines. `gofmt -d` produces a 277-line formatting diff. CI's `golangci-lint` has no format linter enabled so this won't block merge, but the next contributor who runs `make fmt` inherits a noisy reformat commit.

Fix: `gofmt -w lib/screentracker/pty_conversation_test.go`

*(All 6 reviewers flagged this independently: Bisky, Gon, Hisoka, Mafuuu, Meruem, Takumi)*

> 🤖

**Review by mafredri — COMMENTED** [review]
Clean design. Making Phase 1 non-fatal for `WaitTimedOut` while preserving context cancellation as fatal is the right call. The `errors.Is` guard, extracted constants, and 2s timeout are all well-calibrated. Two P2 findings (missing test coverage for the key invariant, gofmt failure), two P3s (doc accuracy, test layering), and a handful of notes.

> *"Oh, this test suite looks lovely! Fifty rows, full coverage, green across the board. It's fake. Every row hits the same code path. You dressed up one test in fifty outfits."* -- Bisky, on a different test. The new tests here are mostly genuine.

Severity count: 0 P0, 0 P1, 2 P2, 2 P3, 3 Notes.

> 🤖 This review was automatically generated with Coder Agents.

File: lib/screentracker/pty_conversation.go [hunk 3]
```diff
@@ -16,6 +17,24 @@ import (
...
+const (
+	// writeStabilizeEchoTimeout is the maximum time to wait for
+	// the screen to change after writing message text to the PTY
+	// (echo detection). This is intentionally short: terminal
+	// echo is near-instant when it occurs. Non-echoing agents
+	// (e.g. TUI agents using bracketed paste) will hit this
+	// timeout, which is non-fatal — see the Phase 1 error
+	// handler in writeStabilize. Move to PTYConversationConfig
+	// if agents need different echo detection windows.
+	writeStabilizeEchoTimeout = 2 * time.Second
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go]: **P3** The doc says "maximum time to wait for the screen to change" but the effective Phase 1 ceiling is ~3s, not 2s. The condition function at line 465 blocks for `1*time.Second` inside WaitFor's condition callback, outside its timeout select. If echo arrives near t=1.7s, the stability check runs until t=2.7s. WaitFor's 2s timeout fires but nobody receives from it until the condition returns.

The 1s stability wait is pre-existing code, but the comment is new. Suggest: "timeout for WaitFor's echo detection loop" instead of "maximum time to wait," or note the stability check can extend past this. *(Hisoka P3, Mafuuu P3)*

PS. The same comment embeds design guidance ("Move to PTYConversationConfig if...") without a `// TODO:` tag. It won't be found in searches. Either make it a TODO or drop it. *(Gon)*

> 🤖

File: lib/screentracker/pty_conversation_test.go (hunk 2 above)
Comment (mafredri) [inline lib/screentracker/pty_conversation_test.go]: **P3** `send-tui-selection-esc-cancels` manually constructs `MessagePartText{Content: "\x1b[200~", Hidden: true}` and asserts the mock saw the bytes the test told it to write. The real bracketed-paste formatting lives in `lib/httpapi/claude.go:formatPaste`. If that function changes (different escape sequence, removed bracketed paste for selection prompts), this test still passes. It documents the limitation but at the wrong layer.

If the intent is pure documentation, a code comment in `formatPaste` is cheaper and equally durable. If the intent is testing, move it to `lib/httpapi` and call `FormatMessage` to get real message parts. *(Bisky P2, downgraded: the PR labels this a documentation test)*

> 🤖

File: lib/screentracker/pty_conversation.go [hunk 4]
```diff
@@ -438,14 +469,25 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
...
+			return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
+		}
+		// Phase 1 timeout is non-fatal: the agent may not echo
+		// input (e.g. TUI agents buffer bracketed-paste content
+		// internally). Proceed to Phase 2 to send the carriage
+		// return.
+		c.cfg.Logger.Info(
+			"screen did not stabilize after writing message, proceeding to send carriage return",
+			"timeout", writeStabilizeEchoTimeout,
+		)
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go:489]: **Note** The log message is 3x longer than every other log in this file (compare: "Tool call detected", "State saved successfully"). It describes two things (what happened + what happens next). The action is implicit from the code. Shorter: `"echo detection timed out, sending carriage return"`. The `"timeout"` structured field already carries the duration. *(Gon)*

> 🤖

File: lib/screentracker/pty_conversation_test.go [hunk 5]
```diff
@@ -447,7 +449,140 @@ func TestMessages(t *testing.T) {
 		c, _, _ := newConversation(context.Background(), t)
 		assert.ErrorIs(t, c.Send(st.MessagePartText{Content: ""}), st.ErrMessageValidationEmpty)
 	})
-}
+
+		t.Run("send-no-echo-agent-reacts", func(t *testing.T) {
```
Comment (mafredri) [inline lib/screentracker/pty_conversation_test.go]: **Note** Two style observations on the new tests:

1. Existing subtests in `TestMessages` use the `send-message-*` prefix (`send-message-status-check`, `send-message-empty-message`). The new ones drop it (`send-no-echo-agent-reacts`). *(Gon)*

2. The new tests manually construct `testAgent`, `quartz.Mock`, `PTYConversationConfig`, `NewPTY`, and `Start`. The existing `newConversation(ctx, t, opts...)` helper already supports overriding `AgentIO` via the options pattern (see lines 240-245). Using it would cut ~15 lines per test. *(Bisky)*

> 🤖

File: lib/screentracker/pty_conversation.go [hunk 6]
```diff
@@ -438,14 +469,25 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
...
 	}
 
 	// wait for the screen to change after the carriage return is written
 	screenBeforeCarriageReturn := c.cfg.AgentIO.ReadScreen()
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go:494]: **Note** If a slow-echo agent changes the screen during Phase 1 but doesn't stabilize before the 2s timeout, Phase 2 captures `screenBeforeCarriageReturn` while the screen is mid-transition. The tail end of the echo settling can satisfy Phase 2's `screen != screenBeforeCarriageReturn` before the agent processes Enter.

Bounded impact: the Enter is in the PTY buffer and will be processed. The PR description acknowledges this. A structural tightening: re-read the screen after Phase 1 timeout to narrow the aliasing window. *(Meruem P3, downgraded to Note: acknowledged in PR, bounded consequence)*

> 🤖

File: lib/screentracker/pty_conversation.go (hunk 4 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:489]: Shortened to `"echo detection timed out, sending carriage return"` in a610148.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation_test.go (hunk 2 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation_test.go]: Agree — dropped the test from screentracker in a610148. Added a doc comment on `formatPaste` in `lib/httpapi/claude.go` instead, noting the ESC limitation and directing callers to `MessageTypeRaw` for selection prompts. Cheaper and equally durable, as Bisky suggested.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation.go (hunk 6 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:494]: Confirmed the re-read is already there — `screenBeforeCarriageReturn := c.cfg.AgentIO.ReadScreen()` runs after Phase 1 returns (line 489), which captures the latest screen state and narrows the aliasing window. No change needed.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation.go (hunk 1 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:478]: Good catch — added `send-message-no-echo-context-cancelled` in a610148. Cancels context during Phase 1 (non-echoing agent), asserts the error wraps `context.Canceled` and does NOT contain the Phase 2 error string.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation.go (hunk 3 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go]: Both fixed in a610148. Comment now reads "timeout for the echo detection WaitFor loop" and notes the 1s stability check can extend past it. Config guidance is now a `// TODO:` tag.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation_test.go (hunk 2 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation_test.go]: Fixed in a610148. All three tests now use `newConversation` with opts callbacks (matching sibling tests), proper single-tab indentation, and correct brace placement. `gofmt -l` is clean. Net -27 lines.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation_test.go (hunk 5 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation_test.go]: Both fixed in a610148. Tests now use `send-message-` prefix and `newConversation(ctx, t, opts...)` with `cfg.AgentIO` overrides.

> 🤖 This response was generated by Coder Agents.

File: lib/screentracker/pty_conversation.go [hunk 7]
```diff
@@ -438,14 +471,25 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
...
-		return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
+		if !errors.Is(err, util.WaitTimedOut) {
+			// Context cancellation or condition errors are fatal.
+			return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
+		}
+		// Phase 1 timeout is non-fatal: the agent may not echo
+		// input (e.g. TUI agents buffer bracketed-paste content
+		// internally). Proceed to Phase 2 to send the carriage
+		// return.
+		c.cfg.Logger.Info(
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:486]: 🤖 Already lowered from `Warn` to `Info` per mafredri's review. `Info` is the right level here — it provides visibility when debugging message delivery issues without polluting warn-level alerting. Lowering to `Debug` would make it invisible in default log configurations, defeating the debuggability purpose.

For agents that never echo, this fires once per message send — the same frequency as existing Info lines like "Tool call detected". Rate-limiting would add complexity for marginal benefit.

File: lib/httpapi/claude.go [hunk 8]
```diff
@@ -5,6 +5,11 @@ import (
 	st "github.com/coder/agentapi/lib/screentracker"
 )
 
+// formatPaste wraps message in bracketed paste escape sequences.
+// These sequences start with ESC (\x1b), which TUI selection
+// widgets (e.g. Claude Code's numbered-choice prompt) interpret
+// as "cancel". For selection prompts, callers should use
+// MessageTypeRaw to send raw keystrokes directly instead.
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply lib/httpapi/claude.go:12]: 🤖 Good catch — the PR description is stale. The `send-tui-selection-esc-cancels` test was dropped during review (mafredri P3: wrong test layer) and replaced with a doc comment on `formatPaste` in `claude.go`. Will update the PR description.

File: lib/screentracker/pty_conversation.go [hunk 9]
```diff
@@ -438,14 +471,25 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
 		}
 		return false, nil
 	}); err != nil {
-		return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
+		if !errors.Is(err, util.WaitTimedOut) {
+			// Context cancellation or condition errors are fatal.
+			return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:480]: 🤖 Pre-existing issue — the `util.After` goroutine leak was flagged by the Go Architect reviewer as an Obs during the deep review. Not introduced by this PR, but now fires more frequently for non-echoing agents (Phase 1 timeout path). Worth a follow-up cleanup to replace `util.After` with an inline timer that gets stopped on cancellation, but out of scope for this fix.

[the remark this answers is not in the document]
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:480]: https://github.com/coder/agentapi/issues/210

**Review by 35C4n0r — APPROVED** [review]
LGTM!

**Comment by 35C4n0r** [comment]
~@johnstcn phase 2 in a different PR ?~
Can you explain what is the intended behaviour ?

**Comment by johnstcn** [comment]
> ~@johnstcn phase 2 in a different PR ?~ Can you explain what is the intended behaviour ?

`writeStabilize` is a two-phase operation. Phase 1 would return a 500 if the screen didn't change. More info in the implementation plan details toggle.

**Comment by 35C4n0r** [comment]
@johnstcn but I still get the 500 response from the server.

run agentapi with claude -> send `/status` -> wait for stabilise -> send a message -> wait till you get a 500

**Comment by johnstcn** [comment]
> @johnstcn but I still get the 500 response from the server.
> 
> run agentapi with claude -> send `/status` -> wait for stabilise -> send a message -> wait till you get a 500

could possibly be also related to https://github.com/coder/agentapi/issues/209 - I have a separate fix for this one in the works

**Comment by 35C4n0r** [comment]
@johnstcn, my bad it's a seperate 500 from phase 2

```
unexpected error occurred: failed to send message: failed to send message: failed to wait for processing to start: timeout waiting for condition
```

File: lib/screentracker/pty_conversation.go [hunk 10]
```diff
@@ -16,6 +17,26 @@ import (
 	"golang.org/x/xerrors"
 )
 
+const (
+	// writeStabilizeEchoTimeout is the timeout for the echo
+	// detection WaitFor loop in writeStabilize Phase 1. The
+	// effective ceiling may be slightly longer because the 1s
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go]: **P3** Comment hard-codes "1s" referencing an unnamed literal at line 464 (`1 * time.Second`). If someone changes that value, the comment goes stale with no compiler or grep to catch it.

Fix: either extract `1 * time.Second` into a named constant (e.g. `writeStabilizeStabilityCheck`) or drop the specific duration from the comment: "the stability check inside the condition runs outside WaitFor's timeout select." *(Gon)*

> 🤖

File: lib/screentracker/pty_conversation_test.go [hunk 11]
```diff
@@ -447,6 +448,130 @@ func TestMessages(t *testing.T) {
...
+		advanceFor(ctx, t, mClock, interval*threshold)
+
+		// When: a message is sent. Phase 1 times out (no echo),
+		// Phase 2 writes \r and the agent reacts.
+		sendAndAdvance(ctx, t, c, mClock, st.MessagePartText{Content: "hello"})
+
+		// Then: Send succeeds and the user message is recorded.
+		msgs := c.Messages()
+		require.True(t, len(msgs) >= 2)
+		var foundUserMsg bool
```
Comment (mafredri) [inline lib/screentracker/pty_conversation_test.go]: **P3** Loop-and-flag is `slices.ContainsFunc` (since 1.21). The project already uses `slices` elsewhere (`lib/httpapi/server.go`). Seven lines to one:

```go
assert.True(t, slices.ContainsFunc(msgs, func(m st.ConversationMessage) bool {
    return m.Role == st.ConversationRoleUser && m.Message == "hello"
}), "expected user message 'hello' in conversation")
```

*(Ging-Go P3, Bisky P3)*

> 🤖

File: lib/screentracker/pty_conversation.go [hunk 12]
```diff
@@ -421,7 +454,7 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
 	}
 	// wait for the screen to stabilize after the message is written
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go]: **Note** The inline comments at line 455 ("wait for the screen to stabilize after the message is written") and line 491 ("wait for the screen to change after the carriage return is written") don't use the Phase 1/Phase 2 vocabulary the doc comment at line 435 introduces. Two vocabularies for the same function. *(Gon)*

> 🤖

File: lib/screentracker/pty_conversation.go [hunk 13]
```diff
@@ -441,14 +474,25 @@ func (c *PTYConversation) writeStabilize(ctx context.Context, messageParts ...Me
 		}
 		return false, nil
 	}); err != nil {
-		return xerrors.Errorf("failed to wait for screen to stabilize: %w", err)
+		if !errors.Is(err, util.WaitTimedOut) {
```
Comment (mafredri) [inline lib/screentracker/pty_conversation.go:478]: **Note** If context cancellation and the 2s timeout fire in the same WaitFor select iteration, Go picks non-deterministically. If the timeout wins, Phase 1 treats it as non-fatal and falls through to Phase 2, which sees `ctx.Done()` immediately and returns the cancellation. The system still fails correctly -- the error wraps through "failed to wait for processing to start" instead of "failed to wait for screen to stabilize." Inherent to Go select; no fix needed. *(Takumi)*

> 🤖

**Review by mafredri — COMMENTED** [review]
Round 2. All 7 findings from round 1 are resolved. The code is cleaner, tests are well-structured, and the core invariant (`errors.Is` guard) is locked down with the context-cancelled test. Three P3s remain, two notes.

Hisoka ran the suite 10x with `-race` and found nothing. Mafuuu traced all four adversarial scenarios. Razor verified every doc claim. Meruem confirmed no structural concerns.

> "Boring code gets silence. This earned it." -- Hisoka

**P3 (convention scan):** Four em-dashes (U+2014) in new code. Replace with ` -- ` or rephrase.
- `lib/screentracker/pty_conversation.go:441`: "this is non-fatal — many TUI"
- `lib/screentracker/pty_conversation.go:446`: "fatal on timeout — if the"
- `lib/screentracker/pty_conversation_test.go:490`: "completely unresponsive — it"
- `lib/screentracker/pty_conversation_test.go:519`: "message parts — this is used"

Severity count: 0 P0, 0 P1, 0 P2, 3 P3, 2 Notes.

> 🤖 This review was automatically generated with Coder Agents.

File: lib/screentracker/pty_conversation.go (hunk 12 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go]: 🤖 Updated both inline comments to use Phase 1/Phase 2 vocabulary in dfd3caa.

File: lib/screentracker/pty_conversation_test.go (hunk 11 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation_test.go]: 🤖 Replaced with `slices.ContainsFunc` in dfd3caa.

File: lib/screentracker/pty_conversation.go (hunk 10 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go]: 🤖 Dropped the specific duration from the comment in dfd3caa.

**Comment by johnstcn** [comment]
🤖 Round 2 feedback addressed in dfd3caa:

- **P3 (hardcoded 1s):** Dropped the specific duration from the `writeStabilizeEchoTimeout` comment
- **P3 (slices.ContainsFunc):** Replaced loop-and-flag with `slices.ContainsFunc`
- **P3 (em-dashes):** Replaced all four U+2014 em-dashes with periods
- **Note (Phase vocabulary):** Updated inline comments at lines 455/491 to use Phase 1/Phase 2 vocabulary

**Review by mafredri — COMMENTED** [review]
Round 3 progress: 4 of 5 open findings from round 2 are addressed in dfd3caa. Good work.

One finding has no author response:

- **F12** (Note, `pty_conversation.go:478`, [thread](https://github.com/coder/agentapi/pull/208#discussion_r3052692735)): Go select non-determinism when context cancellation and Phase 1 timeout race. The reviewer noted this is inherent to Go select and needs no fix, but the thread is unresolved and has no author acknowledgment.

Further review is blocked until the author responds to F12 (even a brief "acknowledged" resolves it) or resolves the thread.

> 🤖 This review was automatically generated with Coder Agents.

File: lib/screentracker/pty_conversation.go (hunk 13 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:478]: As the adoptive author of this code, I hereby acknowledge your note. Thank you for noting.

File: lib/screentracker/pty_conversation_test.go [hunk 14]
```diff
@@ -1179,7 +1298,7 @@ func TestInitialPromptReadiness(t *testing.T) {
 		assert.Equal(t, st.ConversationStatusStable, c.Status())
 	})
 
-	t.Run("no initial prompt - normal status logic applies", func(t *testing.T) {
+	t.Run("ReadyForInitialPrompt always false - status is changing", func(t *testing.T) {
```
Comment (mafredri) [inline lib/screentracker/pty_conversation_test.go:1301]: **Note** Test name uses the Go field name (`ReadyForInitialPrompt`) where siblings use natural language ("agent not ready", "agent becomes ready"). Something like "agent never ready - status is changing" would match the pattern. *(Gon)*

> 🤖

**Review by mafredri — COMMENTED** [review]
All 12 findings from rounds 1-2 are resolved or acknowledged. 6 reviewers + Netero on round 4 found no new issues above P4. One P4, one Note.

Clean work across 4 rounds. The `errors.Is(WaitTimedOut)` guard and `statusLocked` fix are structurally sound -- confirmed independently by Bisky, Mafuuu, Meruem, and Knov. Tests are genuine: each fails without its corresponding production change. Race detector clean.

**P4** `pty_conversation.go:465,504` -- Two duration literals in `writeStabilize` remain unnamed alongside the two extracted constants: `1 * time.Second` (stability check, line 465) and `3*time.Second` (carriage return retry interval, line 504). Someone tuning this function finds two named knobs and two hidden ones -- the 3s retry interval interacts with the 15s process timeout (5 retries max). Pre-existing; the PR extracted the values it changed and left the rest, which is reasonable scoping. *(Gon)*

Knov put it well: *"The statusLocked guard makes the Stable contract honest."*

> 🤖 This review was automatically generated with Coder Agents.

File: lib/screentracker/pty_conversation.go (hunk 13 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation.go:478]: 🤖 Acknowledged. The system fails correctly either way -- the error message differs but the outcome (Send returns an error wrapping context.Canceled) is the same. Inherent to Go select; no fix needed.

**Review by mafredri — APPROVED** [review]

File: lib/screentracker/pty_conversation_test.go (hunk 14 above)
Comment (johnstcn) [reply lib/screentracker/pty_conversation_test.go:1301]: acknowledged
